<?php
require __DIR__ . '/admin/config.php';

$raw_slug = trim((string)($_GET['slug'] ?? ''));
if ($raw_slug === '') {
  http_response_code(404);
  echo 'Produk tidak ditemukan';
  exit;
}

// Load site settings for WA number etc.
$settings = [];
$rs = mysqli_query($conn, "SELECT nama_setting, isi FROM settings");
if ($rs) {
  while ($r = mysqli_fetch_assoc($rs)) $settings[$r['nama_setting']] = $r['isi'];
  mysqli_free_result($rs);
}

// determine whatsapp number prefer kontak_toko.telepon over settings.whatsapp
$wa_number = '';
if (!empty($conn)) {
  $kt = [];
  $rk = @mysqli_query($conn, "SELECT telepon FROM kontak_toko ORDER BY id DESC LIMIT 1");
  if ($rk) {
    $kt = mysqli_fetch_assoc($rk) ?: [];
    mysqli_free_result($rk);
  }
  $tel_source = $kt['telepon'] ?? ($settings['whatsapp'] ?? '');
  if (!empty($tel_source)) {
    $tel = preg_replace('/[^0-9+]/', '', $tel_source);
    if ($tel !== '' && preg_match('/^0/', $tel)) {
      $tel = '62' . preg_replace('/^0+/', '', $tel);
    }
    $wa_number = preg_replace('/[^0-9]/', '', $tel);
  }
}
if ($wa_number === '') {
  $wa_number = '628123456789';
}

// Try exact slug match
$product = null;
$stmt = mysqli_prepare($conn, "SELECT p.*, k.nama_kategori FROM produk p LEFT JOIN kategori_produk k ON p.id_kategori=k.id WHERE p.slug = ? AND p.status = 'aktif' LIMIT 1");
if ($stmt) {
  mysqli_stmt_bind_param($stmt, 's', $raw_slug);
  mysqli_stmt_execute($stmt);
  $res = mysqli_stmt_get_result($stmt);
  $product = mysqli_fetch_assoc($res) ?: null;
  mysqli_stmt_close($stmt);
}

// Fallbacks: if slug looks numeric, try id; or strip random hex suffix (generated by admin)
if (!$product) {
  if (ctype_digit($raw_slug)) {
    $id = (int)$raw_slug;
    $q = mysqli_prepare($conn, "SELECT p.*, k.nama_kategori FROM produk p LEFT JOIN kategori_produk k ON p.id_kategori=k.id WHERE p.id = ? LIMIT 1");
    if ($q) {
      mysqli_stmt_bind_param($q, 'i', $id);
      mysqli_stmt_execute($q);
      $res = mysqli_stmt_get_result($q);
      $product = mysqli_fetch_assoc($res) ?: null;
      mysqli_stmt_close($q);
    }
  }
}

if (!$product) {
  // strip trailing -8hex (admin used bin2hex(random_bytes(4))) and try again
  if (preg_match('/-(?:[0-9a-f]{8})$/i', $raw_slug)) {
    $base = preg_replace('/-(?:[0-9a-f]{8})$/i', '', $raw_slug);
    $s = mysqli_prepare($conn, "SELECT p.*, k.nama_kategori FROM produk p LEFT JOIN kategori_produk k ON p.id_kategori=k.id WHERE p.slug LIKE CONCAT(?, '%') AND p.status='aktif' LIMIT 1");
    if ($s) {
      mysqli_stmt_bind_param($s, 's', $base);
      mysqli_stmt_execute($s);
      $res = mysqli_stmt_get_result($s);
      $product = mysqli_fetch_assoc($res) ?: null;
      mysqli_stmt_close($s);
    }
  }
}

if (!$product) {
  http_response_code(404);
  echo 'Produk tidak ditemukan';
  exit;
}

// Load gambar produk (multiple images support)
$product_images = get_product_images($product['id'], $conn);
// Ensure produk.gambar (legacy main image) is included as slot 0 when not present
if (!empty($product['gambar'])) {
  $mainBasename = basename($product['gambar']);
  $found = false;
  foreach ($product_images as $pi) {
    if (basename($pi['gambar'] ?? '') === $mainBasename) {
      $found = true;
      break;
    }
  }
  if (!$found) {
    array_unshift($product_images, ['id' => 0, 'gambar' => $product['gambar'], 'urutan' => 0, 'is_primary' => 1]);
  }
}
if (empty($product_images)) {
  // Fallback ke gambar lama jika belum migrasi
  if (!empty($product['gambar'])) {
    $product_images = [
      ['id' => 0, 'gambar' => $product['gambar'], 'urutan' => 0, 'is_primary' => 1]
    ];
  }
}

$primary_image = !empty($product_images) ? $product_images[0] : null;
$img = $primary_image ? public_image_url($primary_image['gambar'] ?? '') : public_image_url($product['gambar'] ?? '');

$price = isset($product['harga']) ? number_format((float)$product['harga'], 0, ',', '.') : '-';
$category = htmlspecialchars($product['nama_kategori'] ?? '');
$title = htmlspecialchars($product['nama_produk'] ?? '');
$prod_id = (int)$product['id'];

// Related products (same category, excluding current)
$related = [];
if (!empty($product['id_kategori'])) {
  $rid = (int)$product['id_kategori'];
  $r = mysqli_prepare($conn, "SELECT id, nama_produk, slug, gambar, harga FROM produk WHERE id_kategori = ? AND status='aktif' AND id <> ? ORDER BY created_at DESC LIMIT 4");
  if ($r) {
    mysqli_stmt_bind_param($r, 'ii', $rid, $prod_id);
    mysqli_stmt_execute($r);
    $rs2 = mysqli_stmt_get_result($r);
    while ($row = mysqli_fetch_assoc($rs2)) $related[] = $row;
    mysqli_stmt_close($r);
  }
}

$page_title = $title . ' — Intime Furniture';
include 'partials/header.php';
?>

<body>
  <?php include 'partials/navbar.php'; ?>

  <div class="container-lg mt-3 mb-5" data-aos="fade-up">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb bg-transparent p-0 mb-4">
        <li class="breadcrumb-item"><a href="index.php">Beranda</a></li>
        <?php if ($category): ?><li class="breadcrumb-item"><a href="product.php#product"><?= $category ?></a></li><?php endif; ?>
        <li class="breadcrumb-item active" aria-current="page"><?= $title ?></li>
      </ol>
    </nav>

    <div class="row g-4 align-items-start">
      <div class="col-lg-6">
        <!-- Product Image Gallery -->
        <div class="product-gallery">
          <div class="gallery-main card shadow-sm border-0 mb-4">
            <div class="ratio ratio-1x1">
              <img id="mainImage" src="<?= htmlspecialchars($img) ?>" alt="<?= $title ?>" class="w-100 object-fit-cover rounded" style="max-height:500px; min-height:350px;" />
            </div>
          </div>

          <!-- Thumbnails (if multiple images) -->
          <?php if (count($product_images) > 1): ?>
            <div class="gallery-thumbnails">
              <p class="text-muted small mb-3">Klik gambar untuk melihat lebih besar</p>
              <div class="row g-2">
                <?php foreach ($product_images as $index => $img_item): ?>
                  <div class="col-auto">
                    <img src="<?= htmlspecialchars(public_image_url($img_item['gambar'] ?? '')) ?>"
                      alt="<?= $title ?>"
                      class="thumbnail-img <?= $index === 0 ? 'active' : '' ?>"
                      onclick="changeMainImage(this)"
                      data-image-url="<?= htmlspecialchars(public_image_url($img_item['gambar'] ?? '')) ?>"
                      style="width: 90px; height: 90px; object-fit: cover; border-radius: 6px; cursor: pointer; border: 2px solid transparent; transition: all 0.25s;"
                      title="Klik untuk melihat gambar">
                  </div>
                <?php endforeach; ?>
              </div>
            </div>
          <?php endif; ?>
        </div>
      </div>

      <div class="col-lg-6">
        <h1 class="fw-bold mb-2"><?= $title ?></h1>
        <p class="mb-2"><span class="badge text-bg-secondary"><?= $category ?></span></p>
        <h3 class="fw-bold text-success">Rp <?= $price ?></h3>

        <div class="mt-3">
          <?php $desc_raw = htmlspecialchars($product['deskripsi'] ?? ''); ?>
          <?php if (mb_strlen($desc_raw) > 400): ?>
            <div id="descShort"><?= nl2br(mb_substr($desc_raw, 0, 400)) ?>...</div>
            <div id="descFull" style="display:none"><?= nl2br($desc_raw) ?></div>
            <button id="btnToggleDesc" class="btn btn-link p-0 mt-2">Tampilkan selengkapnya</button>
          <?php else: ?>
            <div id="descShort"><?= nl2br($desc_raw) ?></div>
          <?php endif; ?>
        </div>

        <div class="mt-4 d-flex gap-2">
          <a href="https://wa.me/<?= $wa_number ?>?text=Halo%20saya%20ingin%20memesan%20<?= urlencode($product['nama_produk']) ?>" class="btn btn-success wa-link ms-auto" data-product-id="<?= $prod_id ?>">Pesan Via WhatsApp</a>
          <a href="product.php" class="btn btn-outline-secondary">Kembali</a>
        </div>

        <?php if (!empty($related)): ?>
          <div class="mt-4">
            <h5 class="mb-3">Produk Terkait</h5>
            <div class="row g-3">
              <?php foreach ($related as $rp):
                $rimg = $rp['gambar'] ?? '';
                $rprice = isset($rp['harga']) ? number_format((float)$rp['harga'], 0, ',', '.') : '-';
              ?>
                <div class="col-6 col-md-3">
                  <a href="product_detail.php?slug=<?= urlencode($rp['slug']) ?>" class="text-decoration-none text-dark">
                    <div class="card h-100 shadow-sm">
                      <img src="<?= htmlspecialchars(public_image_url($rimg ?? '')) ?>" class="card-img-top object-fit-cover" style="height:120px;" alt="<?= htmlspecialchars($rp['nama_produk']) ?>">
                      <div class="card-body p-2">
                        <div class="small fw-bold"><?= htmlspecialchars($rp['nama_produk']) ?></div>
                        <div class="small text-success">Rp <?= $rprice ?></div>
                      </div>
                    </div>
                  </a>
                </div>
              <?php endforeach; ?>
            </div>
          </div>
        <?php endif; ?>

      </div>
    </div>
  </div>

  <?php include 'partials/footer.php'; ?>
  <?php include 'partials/scripts.php'; ?>
  <style>
    .product-gallery {
      margin-bottom: 1rem;
    }

    .product-gallery .gallery-main {
      border: 1px solid #e8ecf1;
      border-radius: 8px;
      overflow: hidden;
    }

    .product-gallery .gallery-main .ratio {
      max-height: 500px;
      min-height: 350px;
      overflow: hidden;
    }

    .product-gallery .gallery-thumbnails {
      margin-top: 16px;
      padding-top: 12px;
    }

    .thumbnail-img {
      width: 90px;
      height: 90px;
      object-fit: cover;
      border-radius: 6px;
      cursor: pointer;
      border: 2px solid #e8ecf1;
      transition: all 0.25s ease;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.06);
    }

    .thumbnail-img:hover {
      border-color: #cbd5e1;
      box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1);
      transform: translateY(-1px);
    }

    .thumbnail-img.active {
      border-color: #007bff;
      box-shadow: 0 0 0 3px rgba(0, 123, 255, 0.1), 0 2px 8px rgba(0, 123, 255, 0.15);
    }

    @media (max-width: 767.98px) {
      .product-gallery .gallery-main .ratio {
        max-height: 420px;
        min-height: 300px;
      }

      .gallery-thumbnails {
        overflow-x: auto;
        -webkit-overflow-scrolling: touch;
      }

      .thumbnail-img {
        width: 80px;
        height: 80px;
        flex-shrink: 0;
      }
    }
  </style>

  <script>
    // Gallery thumbnail navigation (uses 'active' class)
    function changeMainImage(thumbnailElement) {
      const mainImage = document.getElementById('mainImage');
      const imageUrl = thumbnailElement.getAttribute('data-image-url') || thumbnailElement.src;
      if (!mainImage || !imageUrl) return;
      mainImage.src = imageUrl;

      // Update active thumbnail styling
      document.querySelectorAll('.thumbnail-img').forEach(img => img.classList.remove('active'));
      thumbnailElement.classList.add('active');
    }

    // Keyboard navigation for gallery
    document.addEventListener('keydown', function(e) {
      const thumbnails = Array.from(document.querySelectorAll('.thumbnail-img'));
      if (thumbnails.length === 0) return;
      const activeIndex = thumbnails.findIndex(img => img.classList.contains('active'));

      if (e.key === 'ArrowUp' || e.key === 'ArrowLeft') {
        if (activeIndex > 0) changeMainImage(thumbnails[activeIndex - 1]);
      } else if (e.key === 'ArrowDown' || e.key === 'ArrowRight') {
        if (activeIndex < thumbnails.length - 1) changeMainImage(thumbnails[activeIndex + 1]);
      }
    });

    // view event already recorded by global script for modal links; send explicit view here
    (function() {
      try {
        var fd = new FormData();
        fd.append('product_id', <?= $prod_id ?>);
        fd.append('event', 'view');
        fetch('admin/track_event.php', {
          method: 'POST',
          body: fd
        }).catch(function() {});
      } catch (e) {}
    })();

    // Toggle product description between short/long versions
    document.addEventListener('DOMContentLoaded', function() {
      var btn = document.getElementById('btnToggleDesc');
      if (!btn) return;

      btn.addEventListener('click', function(e) {
        e.preventDefault();
        var shortDiv = document.getElementById('descShort');
        var fullDiv  = document.getElementById('descFull');
        if (!fullDiv || !shortDiv) return;

        if (fullDiv.style.display === 'none') {
          fullDiv.style.display = '';
          shortDiv.style.display = 'none';
          btn.textContent = 'Sembunyikan';
        } else {
          fullDiv.style.display = 'none';
          shortDiv.style.display = '';
          btn.textContent = 'Tampilkan selengkapnya';
        }
      });
    });
  </script>

</body>

</html>