<?php
require __DIR__ . '/admin/config.php';

$raw_slug = trim((string)($_GET['slug'] ?? ''));
if ($raw_slug === '') {
  http_response_code(404);
  echo 'Produk tidak ditemukan';
  exit;
}

// Load site settings for WA number etc.
$settings = [];
$rs = mysqli_query($conn, "SELECT nama_setting, isi FROM settings");
if ($rs) {
  while ($r = mysqli_fetch_assoc($rs)) $settings[$r['nama_setting']] = $r['isi'];
  mysqli_free_result($rs);
}

// Try exact slug match
$product = null;
$stmt = mysqli_prepare($conn, "SELECT p.*, k.nama_kategori FROM produk p LEFT JOIN kategori_produk k ON p.id_kategori=k.id WHERE p.slug = ? AND p.status = 'aktif' LIMIT 1");
if ($stmt) {
  mysqli_stmt_bind_param($stmt, 's', $raw_slug);
  mysqli_stmt_execute($stmt);
  $res = mysqli_stmt_get_result($stmt);
  $product = mysqli_fetch_assoc($res) ?: null;
  mysqli_stmt_close($stmt);
}

// Fallbacks: if slug looks numeric, try id; or strip random hex suffix (generated by admin)
if (!$product) {
  if (ctype_digit($raw_slug)) {
    $id = (int)$raw_slug;
    $q = mysqli_prepare($conn, "SELECT p.*, k.nama_kategori FROM produk p LEFT JOIN kategori_produk k ON p.id_kategori=k.id WHERE p.id = ? LIMIT 1");
    if ($q) {
      mysqli_stmt_bind_param($q, 'i', $id);
      mysqli_stmt_execute($q);
      $res = mysqli_stmt_get_result($q);
      $product = mysqli_fetch_assoc($res) ?: null;
      mysqli_stmt_close($q);
    }
  }
}

if (!$product) {
  // strip trailing -8hex (admin used bin2hex(random_bytes(4))) and try again
  if (preg_match('/-(?:[0-9a-f]{8})$/i', $raw_slug)) {
    $base = preg_replace('/-(?:[0-9a-f]{8})$/i', '', $raw_slug);
    $s = mysqli_prepare($conn, "SELECT p.*, k.nama_kategori FROM produk p LEFT JOIN kategori_produk k ON p.id_kategori=k.id WHERE p.slug LIKE CONCAT(?, '%') AND p.status='aktif' LIMIT 1");
    if ($s) {
      mysqli_stmt_bind_param($s, 's', $base);
      mysqli_stmt_execute($s);
      $res = mysqli_stmt_get_result($s);
      $product = mysqli_fetch_assoc($res) ?: null;
      mysqli_stmt_close($s);
    }
  }
}

if (!$product) {
  http_response_code(404);
  echo 'Produk tidak ditemukan';
  exit;
}

$img = public_image_url($product['gambar'] ?? '');
$img = str_replace('/project/', '', $img);

$price = isset($product['harga']) ? number_format((float)$product['harga'], 0, ',', '.') : '-';
$category = htmlspecialchars($product['nama_kategori'] ?? '');
$title = htmlspecialchars($product['nama_produk'] ?? '');
$prod_id = (int)$product['id'];

// Related products (same category, excluding current)
$related = [];
if (!empty($product['id_kategori'])) {
  $rid = (int)$product['id_kategori'];
  $r = mysqli_prepare($conn, "SELECT id, nama_produk, slug, gambar, harga FROM produk WHERE id_kategori = ? AND status='aktif' AND id <> ? ORDER BY created_at DESC LIMIT 4");
  if ($r) {
    mysqli_stmt_bind_param($r, 'ii', $rid, $prod_id);
    mysqli_stmt_execute($r);
    $rs2 = mysqli_stmt_get_result($r);
    while ($row = mysqli_fetch_assoc($rs2)) $related[] = $row;
    mysqli_stmt_close($r);
  }
}

$page_title = $title . ' — Intime Furniture';
include 'partials/header.php';
?>

<body>
  <?php include 'partials/navbar.php'; ?>

  <div class="container-lg my-5" data-aos="fade-up">
    <div class="row g-4 align-items-start">
      <div class="col-lg-6">
        <div class="card shadow-sm" data-aos="fade-up">
          <div class="ratio ratio-1x1">
            <img src="<?= htmlspecialchars($img) ?>" alt="<?= $title ?>" class="w-100 object-fit-cover" />
          </div>
        </div>
        <?php if (!empty($related)): ?>
          <div class="mt-4">
            <h5 class="mb-3">Produk Terkait</h5>
            <div class="row g-3">
              <?php foreach ($related as $rp):
                $rimg = $rp['gambar'] ?? '';
                $rprice = isset($rp['harga']) ? number_format((float)$rp['harga'], 0, ',', '.') : '-';
              ?>
                <div class="col-6 col-md-3">
                  <a href="product_detail.php?slug=<?= urlencode($rp['slug']) ?>" class="text-decoration-none text-dark">
                    <div class="card h-100 shadow-sm">
                      <img src="uploads/products/<?= $rimg ?>" class="card-img-top object-fit-cover" style="height:120px;" alt="<?= htmlspecialchars($rp['nama_produk']) ?>">
                      <div class="card-body p-2">
                        <div class="small fw-bold"><?= htmlspecialchars($rp['nama_produk']) ?></div>
                        <div class="small text-success">Rp <?= $rprice ?></div>
                      </div>
                    </div>
                  </a>
                </div>
              <?php endforeach; ?>
            </div>
          </div>
        <?php endif; ?>
      </div>

      <div class="col-lg-6">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb bg-transparent p-0 mb-2">
            <li class="breadcrumb-item"><a href="index.php">Beranda</a></li>
            <?php if ($category): ?><li class="breadcrumb-item"><a href="product.php#product"><?= $category ?></a></li><?php endif; ?>
            <li class="breadcrumb-item active" aria-current="page"><?= $title ?></li>
          </ol>
        </nav>

        <h1 class="fw-bold mb-2"><?= $title ?></h1>
        <p class="mb-2"><span class="badge text-bg-secondary"><?= $category ?></span></p>
        <h3 class="fw-bold text-success">Rp <?= $price ?></h3>

        <div class="mt-3">
          <?= nl2br(htmlspecialchars($product['deskripsi'] ?? '')) ?>
        </div>

        <div class="mt-4 d-flex gap-2">
          <a href="https://wa.me/<?= isset($settings['whatsapp']) ? preg_replace('/[^0-9]/', '', $settings['whatsapp']) : '628123456789' ?>?text=Halo%20saya%20ingin%20memesan%20<?= urlencode($product['nama_produk']) ?>" class="btn btn-success wa-link ms-auto" data-product-id="<?= $prod_id ?>">Pesan Via WhatsApp</a>
          <a href="product.php" class="btn btn-outline-secondary">Kembali</a>
        </div>

      </div>
    </div>
  </div>

  <?php include 'partials/footer.php'; ?>
  <?php include 'partials/scripts.php'; ?>

  <script>
    // view event already recorded by global script for modal links; send explicit view here
    (function() {
      try {
        var fd = new FormData();
        fd.append('product_id', <?= $prod_id ?>);
        fd.append('event', 'view');
        fetch('admin/track_event.php', {
          method: 'POST',
          body: fd
        }).catch(function() {});
      } catch (e) {}
    })();
  </script>

</body>

</html>